defaults: &defaults
  adapter: sqlite

development:
  database: db/development.db
  <<: *defaults

test:
  database: db/test.db
  <<: *defaults

production:
  database: db/production.db
  <<: *defaults
